# Nome da aplicação
spring.application.name=lojinha-api

# Configuração do Banco de Dados H2
spring.datasource.url=jdbc:h2:mem:lojinhadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilita o console do H2 no navegador (http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Mostra no console do Java o SQL gerado pelo Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true